guard 'zeus' do
  watch(%r{config/.*/.+\.rb})
  watch(%r{config/.+\.rb})
  watch(%r{spec/support/.+\.rb})
  watch(%r{spec/support/.*/.+\.rb})
  watch(%r{spec/.+\.rb})
  watch(%r{Gemfile})
  watch(%r{Gemfile.lock})
end
